server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8


cos:
  qcloud:
    secret:
      id:
      key:
    token:
      expire:
        millis: 300000
    download:
      url:
        expire:
          millis: 86400000
    bucket: idopy-1253901570
    region: ap-beijing
    host: https://idopy-1253901570.cos.ap-beijing.myqcloud.com
    upload:
      path: /upload/